package com.bn.appium.alchemy.utils;

/**
 * Created by avsupport on 3/5/14.
 */
public enum ConfigurationParametersEnum {
    MOBILE_PLATFORM,


    BUILD_DIR,
    BUILD_NAME,
    IOS_PLATFORM_VERSION,
    IOS_PLATFORM_NAME,
    IOS_APP_PACKAGE,
    IOS_DEVICE_ID,
    IOS_DEVICE,

    LOGIN,
    PASSWORD,
    NET,
    BUILD,
    TIMEOUT,
    SYNC_COMPLETE,

    SEARCH_BOOK_NAME,
    LOAD_BOOK_NAME,
    MAX_LOAD_TIME,

    BOOK,
    BOOK_SIZE,

    DRP_CATALOG,
    DRP_CATALOG_SIZE,


    VIDEO_BOOK,
    VIDEO_BOOK_SIZE,

    DRP_MAGAZINE,
    MAGAZINE_SIZE,

    PDF,
    PDF_SIZE,

    WOODWIN_MAGAZINE,
    WOODWIN_SIZE,

    DRP_COMICS,
    DRP_COMICS_SIZE,

    NEWSPAPER,
    NEWSPAPER_SIZE,

    EPIB,
    EPIB_SIZE,

    DATE_FIELD_NAME,
    TIME_FIELD_NAME,
    BUILD_FIELD_NAME,
    HW_FIELD_NAME,
    OS_FIELD_NAME,
    NET_FIELD_NAME,
    DEVICE_ID_FIELD_NAME,
    SLAVE_ID_FIELD_NAME,
    TEST_TYPE_FIELD_NAME,
    TEST_ID_FIELD_NAME,
    TEST_NAME_FIELD_NAME,
    TEST_ACTION_FIELD_NAME,
    TEST_DATA_FIELD_NAME,
    USED_MEMORY_FIELD_NAME,
    START_TIME_FIELD_NAME,
    END_TIME_FIELD_NAME,
    TOTAL_TIME_FIELD_NAME,
    TEST_RESULT_FIELD_NAME,
    TEST_CYCLE_FIELD_NAME,
    DUMP_KPI_INFO,
    ConfigurationParametersEnum;

}
